services:
  - type: web
    name: creative-minds-backend
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@creativeminds.in
      - key: ADMIN_PASS
        value: Admin@CM2025

